@BASE_URL=http://localhost:3000/api

### Create User
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "Andy",
    "userName": "andy",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "admin"
}